
// Code generated by stanc v2.29.0
#include <stan/model/model_header.hpp>
namespace simplified_ppc_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 32> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 33, column 2 to column 44)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 34, column 2 to column 45)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 35, column 2 to column 45)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 36, column 2 to column 20)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 38, column 4 to column 18)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 39, column 4 to column 20)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 40, column 4 to column 21)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 42, column 4 to column 61)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 37, column 2 to line 43, column 3)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 46, column 2 to column 78)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 21, column 2 to column 22)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 22, column 2 to column 13)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 23, column 2 to column 10)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 24, column 10 to column 16)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 24, column 2 to column 18)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 25, column 2 to column 8)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 28, column 2 to column 14)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 29, column 2 to column 21)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 36, column 9 to column 15)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 46, column 13 to column 19)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 5, column 6 to column 20)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 6, column 6 to column 20)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 7, column 6 to column 20)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 8, column 6 to column 22)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 10, column 6 to column 27)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 11, column 6 to column 28)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 13, column 6 to column 29)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 14, column 6 to column 41)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 15, column 6 to column 30)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 17, column 6 to column 35)",
 " (in '/Users/piotrszyller/Documents/2ndLv/s01/DataAnalytics/New/simplified_ppc.stan', line 3, column 36 to line 18, column 3)"};

struct sir_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            stan::require_stan_scalar_t<T0__>* = nullptr,
            stan::require_stan_scalar_t<T1__>* = nullptr,
            stan::require_stan_scalar_t<T2__>* = nullptr,
            stan::require_stan_scalar_t<T3__>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  operator()(const T0__& t, const std::vector<T1__>& y,
             const std::vector<T2__>& theta, const std::vector<T3__>& x_r,
             const std::vector<int>& x_i, std::ostream* pstream__) const;
};

template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_stan_scalar_t<T0__>* = nullptr,
          stan::require_stan_scalar_t<T1__>* = nullptr,
          stan::require_stan_scalar_t<T2__>* = nullptr,
          stan::require_stan_scalar_t<T3__>* = nullptr>
  std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
  sir(const T0__& t, const std::vector<T1__>& y,
      const std::vector<T2__>& theta, const std::vector<T3__>& x_r,
      const std::vector<int>& x_i, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ S = DUMMY_VAR__;
      current_statement__ = 21;
      S = stan::model::rvalue(y, "y", stan::model::index_uni(1));
      local_scalar_t__ I = DUMMY_VAR__;
      current_statement__ = 22;
      I = stan::model::rvalue(y, "y", stan::model::index_uni(2));
      local_scalar_t__ R = DUMMY_VAR__;
      current_statement__ = 23;
      R = stan::model::rvalue(y, "y", stan::model::index_uni(3));
      local_scalar_t__ N = DUMMY_VAR__;
      current_statement__ = 24;
      N = stan::model::rvalue(x_i, "x_i", stan::model::index_uni(1));
      local_scalar_t__ beta = DUMMY_VAR__;
      current_statement__ = 25;
      beta = stan::model::rvalue(theta, "theta", stan::model::index_uni(1));
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 26;
      gamma = stan::model::rvalue(theta, "theta", stan::model::index_uni(2));
      local_scalar_t__ dS_dt = DUMMY_VAR__;
      current_statement__ = 27;
      dS_dt = (-beta * S);
      local_scalar_t__ dI_dt = DUMMY_VAR__;
      current_statement__ = 28;
      dI_dt = ((beta * S) - (gamma * I));
      local_scalar_t__ dR_dt = DUMMY_VAR__;
      current_statement__ = 29;
      dR_dt = (gamma * I);
      current_statement__ = 30;
      return std::vector<local_scalar_t__>{dS_dt, dI_dt, dR_dt};
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_stan_scalar_t<T0__>*,
          stan::require_stan_scalar_t<T1__>*,
          stan::require_stan_scalar_t<T2__>*,
          stan::require_stan_scalar_t<T3__>*>
std::vector<stan::promote_args_t<T0__, T1__, T2__, T3__>>
sir_functor__::operator()(const T0__& t, const std::vector<T1__>& y,
                          const std::vector<T2__>& theta,
                          const std::vector<T3__>& x_r,
                          const std::vector<int>& x_i,
                          std::ostream* pstream__)  const
{
  return sir(t, y, theta, x_r, x_i, pstream__);
}


class simplified_ppc_model final : public model_base_crtp<simplified_ppc_model> {

 private:
  int n_days;
  std::vector<double> y0;
  double t0;
  std::vector<double> ts;
  int N;
  std::vector<double> x_r;
  std::vector<int> x_i; 
  
 
 public:
  ~simplified_ppc_model() { }
  
  inline std::string model_name() const final { return "simplified_ppc_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.0", "stancflags = "};
  }
  
  
  simplified_ppc_model(stan::io::var_context& context__,
                       unsigned int random_seed__ = 0,
                       std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "simplified_ppc_model_namespace::simplified_ppc_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 11;
      context__.validate_dims("data initialization","n_days","int",
           std::vector<size_t>{});
      n_days = std::numeric_limits<int>::min();
      
      
      current_statement__ = 11;
      n_days = context__.vals_i("n_days")[(1 - 1)];
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "n_days", n_days, 1);
      current_statement__ = 12;
      context__.validate_dims("data initialization","y0","double",
           std::vector<size_t>{static_cast<size_t>(3)});
      y0 = std::vector<double>(3, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 12;
      y0 = context__.vals_r("y0");
      current_statement__ = 13;
      context__.validate_dims("data initialization","t0","double",
           std::vector<size_t>{});
      t0 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 13;
      t0 = context__.vals_r("t0")[(1 - 1)];
      current_statement__ = 14;
      stan::math::validate_non_negative_index("ts", "n_days", n_days);
      current_statement__ = 15;
      context__.validate_dims("data initialization","ts","double",
           std::vector<size_t>{static_cast<size_t>(n_days)});
      ts = 
        std::vector<double>(n_days, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 15;
      ts = context__.vals_r("ts");
      current_statement__ = 16;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 16;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 17;
      x_r = std::vector<double>(0, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 18;
      x_i = std::vector<int>(1, std::numeric_limits<int>::min());
      
      
      current_statement__ = 18;
      stan::model::assign(x_i, std::vector<int>{N}, "assigning variable x_i");
      current_statement__ = 19;
      stan::math::validate_non_negative_index("y", "n_days", n_days);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("cases", "n_days", n_days);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 0U;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "simplified_ppc_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "simplified_ppc_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      beta = stan::math::normal_rng(0.6, 0.3, base_rng__);
      double gamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      gamma = stan::math::normal_rng(0.2, 0.4, base_rng__);
      double phi_inv = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      phi_inv = stan::math::exponential_rng(5, base_rng__);
      std::vector<std::vector<double>> y =
         std::vector<std::vector<double>>(n_days, 
           std::vector<double>(3, std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<double> theta =
           std::vector<double>(2, std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 6;
        stan::model::assign(theta, beta,
          "assigning variable theta", stan::model::index_uni(1));
        current_statement__ = 7;
        stan::model::assign(theta, gamma,
          "assigning variable theta", stan::model::index_uni(2));
        current_statement__ = 8;
        stan::model::assign(y,
          stan::math::integrate_ode_rk45(sir_functor__(), y0, t0, ts, theta,
            x_r, x_i, pstream__), "assigning variable y");
      }
      std::vector<double> cases =
         std::vector<double>(n_days, 
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 10;
      stan::model::assign(cases,
        stan::math::neg_binomial_2_rng(
          stan::math::col(stan::math::to_matrix(y), 2), (1. / phi_inv),
          base_rng__), "assigning variable cases");
      current_statement__ = 1;
      stan::math::check_greater_or_equal(function__, "beta", beta, 0);
      current_statement__ = 2;
      stan::math::check_greater_or_equal(function__, "gamma", gamma, 0);
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "phi_inv", phi_inv, 0);
      out__.write(beta);
      out__.write(gamma);
      out__.write(phi_inv);
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n_days; ++sym2__) {
          out__.write(y[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(cases);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"beta", "gamma", "phi_inv", "y",
      "cases"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(n_days), static_cast<size_t>(3)},
      std::vector<size_t>{static_cast<size_t>(n_days)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "beta");
      param_names__.emplace_back(std::string() + "gamma");
      param_names__.emplace_back(std::string() + "phi_inv");
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_days; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "y" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      for (int sym1__ = 1; sym1__ <= n_days; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "cases" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "beta");
      param_names__.emplace_back(std::string() + "gamma");
      param_names__.emplace_back(std::string() + "phi_inv");
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_days; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "y" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      for (int sym1__ = 1; sym1__ <= n_days; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "cases" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"phi_inv\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"y\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_days) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(3) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"cases\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_days) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"phi_inv\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"y\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_days) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(3) + ",\"element_type\":{\"name\":\"real\"}}},\"block\":\"generated_quantities\"},{\"name\":\"cases\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_days) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  ((((1 + 1) + 1) + (n_days * 3)) + n_days);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  ((((1 + 1) + 1) + (n_days * 3)) + n_days);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 0> names__{};
      const std::array<Eigen::Index, 0> constrain_param_sizes__{};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } 
using stan_model = simplified_ppc_model_namespace::simplified_ppc_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return simplified_ppc_model_namespace::profiles__;
}

#endif


